[app]
host = "127.0.0.1"
port = 8000


[log]
level = "info"
path = "app.log"


[database]
host = "127.0.0.1"
name = "ai_summary"
user = "root"
password = "12345678"
port = 3306
param = "useUnicode=true%26characterEncoding=utf8%26useOldAliasMetadataBehavior=true%26zeroDateTimeBehavior=convertToNull%26allowMultiQueries=true%26serverTimezone=GMT%2b8"

